name: checks & tests

on: push

jobs:
  checks:
    name: Quality & Security checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Linters
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.54.1
          args: --verbose
  tests:
    name: Tests with coverage
    runs-on: ubuntu-latest
    needs: checks
    services:
      redis:
        image: redislabs/redisearch:latest
        ports:
          - 9002:6379
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure MySQL & Create databases
        run: |
          sudo bash -c 'echo -e "[mysqld]\nport=9004\n" >> /etc/mysql/my.cnf'
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE hitrix;' -uroot -proot

      - name: Run tests with coverage
        run: |
          make test-cover

      - name: Upload report to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}